import './globals.css'
import Navbar from './components/Navbar'
import { Noto_Sans_Display } from 'next/font/google'

const NotoSans = Noto_Sans_Display({ 
  weight: ['400', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'] 
})

export const metadata = {
  title: 'Gondang Ria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${NotoSans.className} overflow-x-hidden`}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
